/* ============================================================
   InnovateX — Rich Demo Data
   js/data.js
   ============================================================ */

const IX = {

  /* ── State ─────────────────────────────────────────────── */
  state: { role: 'visitor', currentProblemId: 'p001', user: null },

  roles: {
    visitor:      { label: 'Visitor', icon: '👤' },
    startup:      { label: 'Startup / Solution Provider', icon: '🚀' },
    organization: { label: 'Problem Owner / Organization', icon: '🏢' },
    expert:       { label: 'Expert Reviewer', icon: '🧑‍⚖️' },
    admin:        { label: 'Admin', icon: '🛡️' },
  },

  /* ── Global Stats ────────────────────────────────────────*/
  stats: {
    total_problems:    47,
    total_solutions:   312,
    organizations:      38,
    teams:             189,
    collaborations:     24,
    active_pilots:       8,
    completed_pilots:   14,
    success_rate:       78,
  },

  /* ── Categories ─────────────────────────────────────────── */
  categories: [
    { id:'agriculture',   name:'Agriculture',    icon:'🌾', color:'#16A34A', bg:'#F0FDF4', problems:18, solutions:74,  desc:'Smart farming, crop monitoring, irrigation, and sustainable agriculture solutions.' },
    { id:'healthcare',    name:'Healthcare',     icon:'🏥', color:'#DC2626', bg:'#FFF1F2', problems:15, solutions:89,  desc:'Affordable diagnostics, telemedicine, rural health, and medical innovation.' },
    { id:'technology',    name:'Technology',     icon:'💻', color:'#2563EB', bg:'#EFF6FF', problems:12, solutions:61,  desc:'Software platforms, AI tools, and digital infrastructure for innovation.' },
    { id:'education',     name:'Education',      icon:'🎓', color:'#7C3AED', bg:'#FAF5FF', problems:10, solutions:48,  desc:'Personalized learning, EdTech platforms, and accessible education.' },
    { id:'environment',   name:'Environment',    icon:'🌿', color:'#059669', bg:'#F0FDFA', problems: 9, solutions:37,  desc:'Waste management, pollution control, recycling, and green innovation.' },
    { id:'finance',       name:'Finance',        icon:'💰', color:'#D97706', bg:'#FFFBEB', problems: 8, solutions:32,  desc:'Financial inclusion, digital payments, microfinance, and fintech.' },
    { id:'transport',     name:'Transportation', icon:'🚗', color:'#0891B2', bg:'#F0F9FF', problems: 7, solutions:28,  desc:'Smart mobility, logistics, public transport, and urban connectivity.' },
    { id:'smartcities',   name:'Smart Cities',   icon:'🏙️', color:'#4F46E5', bg:'#EEF2FF', problems: 6, solutions:22,  desc:'Urban planning, civic tech, digital governance, and smart infrastructure.' },
    { id:'government',    name:'Government',     icon:'🏛️', color:'#7C3AED', bg:'#FAF5FF', problems: 5, solutions:19,  desc:'Digital public services, e-governance, and policy innovation.' },
    { id:'energy',        name:'Energy',         icon:'⚡', color:'#CA8A04', bg:'#FEFCE8', problems: 5, solutions:21,  desc:'Renewable energy, energy efficiency, and grid modernization.' },
    { id:'retail',        name:'Retail',         icon:'🛒', color:'#DB2777', bg:'#FDF2F8', problems: 4, solutions:16,  desc:'Local commerce, demand forecasting, and retail innovation.' },
    { id:'manufacturing', name:'Manufacturing',  icon:'🏭', color:'#64748B', bg:'#F8FAFC', problems: 4, solutions:14,  desc:'Industry 4.0, predictive maintenance, and supply chain optimization.' },
    { id:'socialimpact',  name:'Social Impact',  icon:'🤲', color:'#0D9488', bg:'#F0FDFA', problems: 4, solutions:18,  desc:'Assistive technology, disability inclusion, and social innovation.' },
    { id:'cybersecurity', name:'Cybersecurity',  icon:'🔒', color:'#1E40AF', bg:'#EFF6FF', problems: 3, solutions:12,  desc:'SME cybersecurity, data privacy, and digital threat protection.' },
    { id:'other',         name:'Other',          icon:'💡', color:'#6B7280', bg:'#F9FAFB', problems: 5, solutions:21,  desc:'Cross-domain problems that don\'t fit neatly into other categories.' },
  ],

  /* ── Organizations ────────────────────────────────────── */
  orgs: [
    { id:'o1', name:'National Agriculture Innovation Lab', short:'NAIL', category:'agriculture', location:'New Delhi', logo:'🌾' },
    { id:'o2', name:'Apollo Health Foundation',            short:'AHF',  category:'healthcare',  location:'Mumbai',    logo:'🏥' },
    { id:'o3', name:'AICTE Innovation Cell',               short:'AIC',  category:'technology',  location:'New Delhi', logo:'🎓' },
    { id:'o4', name:'Smart City Mission India',            short:'SCMI', category:'smartcities', location:'Pune',      logo:'🏙️' },
    { id:'o5', name:'Invest India',                        short:'II',   category:'finance',     location:'New Delhi', logo:'💰' },
    { id:'o6', name:'Ministry of Education',               short:'MoE',  category:'education',   location:'New Delhi', logo:'📚' },
    { id:'o7', name:'TERI Foundation',                     short:'TERI', category:'environment', location:'Bangalore', logo:'🌿' },
    { id:'o8', name:'National Transport Authority',         short:'NTA',  category:'transport',   location:'Chennai',   logo:'🚗' },
  ],

  /* ── Teams / Startups ─────────────────────────────────── */
  teams: [
    { id:'t1',  name:'AgriNova',       logo:'🌱', category:'agriculture', location:'Pune',      desc:'AI-powered precision agriculture solutions for smallholder farmers.', solutions:2, score:91,
      verification:{ eligibility:'eligible', ix_status:'verified', dpiit:'dpiit_recognized', dpiit_no:'DIPP12345', startup_status:'startup_recognized' } },
    { id:'t2',  name:'FarmVision',     logo:'🛰️', category:'agriculture', location:'Hyderabad', desc:'Satellite imagery and remote sensing for crop monitoring.', solutions:1, score:89,
      verification:{ eligibility:'eligible', ix_status:'verified', dpiit:'application_pending', dpiit_no:null, startup_status:'active' } },
    { id:'t3',  name:'BioWatch',       logo:'⌚', category:'healthcare',  location:'Bangalore', desc:'Wearable diagnostic devices for rural healthcare access.', solutions:2, score:87,
      verification:{ eligibility:'eligible', ix_status:'verified', dpiit:'dpiit_recognized', dpiit_no:'DIPP67890', startup_status:'startup_recognized' } },
    { id:'t4',  name:'RuralHealth Labs',logo:'🏥', category:'healthcare', location:'Chennai',   desc:'Low-cost telemedicine platforms for tier-2 and tier-3 cities.', solutions:1, score:84,
      verification:{ eligibility:'eligible', ix_status:'under_review', dpiit:'not_claimed', dpiit_no:null, startup_status:'active' } },
    { id:'t5',  name:'NurseAI',        logo:'👩‍⚕️', category:'healthcare', location:'Mumbai',   desc:'AI voice assistant for multilingual nurse support systems.', solutions:1, score:82,
      verification:{ eligibility:'potentially_eligible', ix_status:'pending', dpiit:'not_claimed', dpiit_no:null, startup_status:'active' } },
    { id:'t6',  name:'EduBridge',      logo:'🎓', category:'education',   location:'Delhi',     desc:'Adaptive learning platform for first-generation college students.', solutions:1, score:88,
      verification:{ eligibility:'eligible', ix_status:'verified', dpiit:'under_review', dpiit_no:null, startup_status:'active' } },
    { id:'t7',  name:'LearnSphere',    logo:'📚', category:'education',   location:'Jaipur',    desc:'Regional-language learning tools powered by NLP.', solutions:1, score:83,
      verification:{ eligibility:'eligible', ix_status:'pending', dpiit:'not_claimed', dpiit_no:null, startup_status:'active' } },
    { id:'t8',  name:'GreenLoop',      logo:'♻️', category:'environment', location:'Mumbai',    desc:'Waste segregation and recycling optimization using computer vision.', solutions:1, score:86,
      verification:{ eligibility:'eligible', ix_status:'verified', dpiit:'application_pending', dpiit_no:null, startup_status:'active' } },
    { id:'t9',  name:'AquaSense',      logo:'💧', category:'smartcities', location:'Ahmedabad', desc:'IoT-based smart water management for urban municipalities.', solutions:1, score:85,
      verification:{ eligibility:'eligible', ix_status:'verified', dpiit:'dpiit_recognized', dpiit_no:'DIPP54321', startup_status:'startup_recognized' } },
    { id:'t10', name:'CivicStack',     logo:'🏛️', category:'government',  location:'Bhopal',   desc:'Digital identity and e-governance platforms for public services.', solutions:1, score:82,
      verification:{ eligibility:'potentially_eligible', ix_status:'needs_info', dpiit:'not_claimed', dpiit_no:null, startup_status:'active' } },
    { id:'t11', name:'TransitIQ',      logo:'🚌', category:'transport',   location:'Kolkata',   desc:'Predictive maintenance analytics for urban public transport fleets.', solutions:1, score:80,
      verification:{ eligibility:'eligible', ix_status:'pending', dpiit:'not_claimed', dpiit_no:null, startup_status:'active' } },
    { id:'t12', name:'CyberShield',    logo:'🛡️', category:'cybersecurity',location:'Bengaluru',desc:'SME-focused cybersecurity as a service platform.', solutions:1, score:81,
      verification:{ eligibility:'eligible', ix_status:'verified', dpiit:'application_pending', dpiit_no:null, startup_status:'active' } },
    { id:'t13', name:'EcoGrid',        logo:'⚡', category:'energy',      location:'Surat',     desc:'Energy optimization SaaS for industrial and commercial facilities.', solutions:1, score:84,
      verification:{ eligibility:'eligible', ix_status:'verified', dpiit:'dpiit_recognized', dpiit_no:'DIPP11223', startup_status:'startup_recognized' } },
    { id:'t14', name:'VoiceAgri',      logo:'🎙️', category:'agriculture', location:'Nagpur',    desc:'Voice-based advisory and market pricing for rural farmers.', solutions:1, score:79,
      verification:{ eligibility:'eligible', ix_status:'under_review', dpiit:'under_review', dpiit_no:null, startup_status:'active' } },
    { id:'t15', name:'SepsisSense',    logo:'🧠', category:'healthcare',  location:'Delhi',     desc:'Edge AI for early sepsis detection in rural ICUs.', solutions:1, score:94,
      verification:{ eligibility:'eligible', ix_status:'verified', dpiit:'dpiit_recognized', dpiit_no:'DIPP99887', startup_status:'startup_recognized' } },
  ],

  /* ── Problems (rich dataset) ──────────────────────────── */
  problems: [
    {
      id:'p001', category:'agriculture', org_id:'o1',
      title:'Early Crop Disease Detection for Small Farmers',
      org:'National Agriculture Innovation Lab',
      location:'Pan India',
      difficulty:2, status:'open', stage:'shortlisting',
      solutions_count:7, deadline:'2026-10-20',
      impact:'high', prize:'₹20 Lakhs',
      tags:['AI/ML','Mobile','Agriculture','Computer Vision'],
      desc:'Small farmers lose 30–40% of crops annually to diseases detected too late. Build an affordable mobile-based AI solution to help farmers identify crop diseases early using smartphone cameras.',
      why_matters:'Over 100 million smallholder farmers in India lack access to expert agronomists. Early detection can prevent up to 40% crop loss and increase farmer income by ₹15,000 per season.',
      constraints:'Must work offline, must support 10+ regional languages, cost per farmer must be under ₹50/month.',
      expected_outcome:'A deployable mobile app achieving >85% disease detection accuracy across 20+ common crops.',
    },
    {
      id:'p002', category:'healthcare', org_id:'o2',
      title:'Affordable Rural Healthcare Diagnostics',
      org:'Apollo Health Foundation',
      location:'Maharashtra, Rajasthan',
      difficulty:3, status:'open', stage:'ai_analysis',
      solutions_count:5, deadline:'2026-10-30',
      impact:'very_high', prize:'₹25 Lakhs',
      tags:['Healthcare','IoT','Edge AI','Diagnostics'],
      desc:'Rural India has 1 doctor per 11,000 people. Build affordable diagnostic tools that enable frontline health workers to conduct preliminary screening for common conditions.',
      why_matters:'Preventable diseases cause 60% of rural deaths. Early diagnosis can reduce mortality by up to 45% and save the healthcare system ₹4,000 per case avoided.',
      constraints:'Must be usable by ASHA workers with minimal training, cost per diagnosis under ₹30, offline-capable.',
      expected_outcome:'A portable diagnostic kit with software achieving >90% accuracy in screening TB, anaemia, and diabetes.',
    },
    {
      id:'p003', category:'smartcities', org_id:'o4',
      title:'Smart Water Management for Cities',
      org:'Smart City Mission India',
      location:'Pune, Nashik',
      difficulty:2, status:'open', stage:'collaboration',
      solutions_count:4, deadline:'2026-11-15',
      impact:'high', prize:'₹18 Lakhs',
      tags:['IoT','Smart Cities','Water','Analytics'],
      desc:'Urban water wastage reaches 40% in Indian cities due to leaky pipes, inefficient distribution, and lack of real-time monitoring. Develop a smart water monitoring and management system.',
      why_matters:'India faces a water crisis by 2030. Smart monitoring can reduce waste by 30%, saving municipalities ₹500 crore annually across major cities.',
      constraints:'Must integrate with existing SCADA systems, real-time alerts, API for municipal dashboards.',
      expected_outcome:'IoT sensor network with analytics dashboard achieving 25% reduction in water wastage within 6 months.',
    },
    {
      id:'p004', category:'education', org_id:'o6',
      title:'Personalized Learning for Rural Students',
      org:'Ministry of Education',
      location:'Pan India',
      difficulty:2, status:'open', stage:'solutions',
      solutions_count:6, deadline:'2026-11-30',
      impact:'high', prize:'₹15 Lakhs',
      tags:['EdTech','AI','NLP','Mobile'],
      desc:'Rural students in grades 6–10 lack personalized attention. Only 35% pass Class 10 with acceptable scores. Build an adaptive AI tutoring platform that works in regional languages.',
      why_matters:'Personalized learning can improve student outcomes by 25–40%. With 250 million school children, even 5% improvement represents millions of lives changed.',
      constraints:'Low-bandwidth compatibility, support for 8 languages, work on budget Android devices.',
      expected_outcome:'AI tutoring app showing >25% improvement in learning outcomes over 6 months in pilot schools.',
    },
    {
      id:'p005', category:'environment', org_id:'o7',
      title:'Waste Segregation and Recycling Optimization',
      org:'TERI Foundation',
      location:'Mumbai, Delhi',
      difficulty:2, status:'open', stage:'solutions',
      solutions_count:3, deadline:'2026-12-10',
      impact:'medium', prize:'₹12 Lakhs',
      tags:['Computer Vision','IoT','Sustainability','Smart Cities'],
      desc:'India generates 62 million tonnes of waste annually, with only 22% properly segregated. Build an AI-powered waste segregation system for residential communities and municipalities.',
      why_matters:'Proper segregation can increase recycling rates from 22% to 60%, reducing landfill use, creating 500,000 jobs, and generating ₹10,000 crore in recycled materials annually.',
      constraints:'Must handle wet, dry, and hazardous waste categories, cost-effective for municipal deployment.',
      expected_outcome:'Computer vision system with >92% segregation accuracy and a citizen-facing mobile app.',
    },
    {
      id:'p006', category:'government', org_id:'o8',
      title:'Secure Digital Identity for Public Services',
      org:'National Transport Authority',
      location:'Pan India',
      difficulty:3, status:'open', stage:'solutions',
      solutions_count:3, deadline:'2026-12-20',
      impact:'high', prize:'₹22 Lakhs',
      tags:['Blockchain','Identity','Government','Security'],
      desc:'Citizens need secure, privacy-preserving digital identities for accessing government services without carrying physical documents or exposing sensitive data.',
      why_matters:'Fraud in public service delivery costs India ₹12,000 crore annually. Secure digital identity can eliminate ghost beneficiaries and ensure right targeting of welfare schemes.',
      constraints:'Must comply with data protection laws, privacy-by-design, work for citizens with limited digital literacy.',
      expected_outcome:'A blockchain-backed identity solution with 99.9% uptime, usable by 100 million citizens within 18 months.',
    },
    {
      id:'p007', category:'transport', org_id:'o8',
      title:'Predictive Maintenance for Public Transport',
      org:'National Transport Authority',
      location:'Kolkata, Chennai',
      difficulty:2, status:'open', stage:'ai_analysis',
      solutions_count:4, deadline:'2026-11-10',
      impact:'medium', prize:'₹14 Lakhs',
      tags:['IoT','Predictive Analytics','Transport','ML'],
      desc:'Unplanned bus breakdowns cause 35% service disruption in city fleets. Build an IoT and ML-based predictive maintenance system that identifies failure risks before they occur.',
      why_matters:'Each unplanned breakdown costs ₹25,000 in repairs and service loss. Preventing 70% of breakdowns can save city transport authorities ₹150 crore annually.',
      constraints:'Must integrate with existing fleet management systems, work with legacy vehicles, real-time alerts.',
      expected_outcome:'Predictive system reducing breakdown rate by 60% and maintenance costs by 35%.',
    },
    {
      id:'p008', category:'finance', org_id:'o5',
      title:'Financial Inclusion for Underserved Communities',
      org:'Invest India',
      location:'Bihar, UP, Odisha',
      difficulty:2, status:'open', stage:'solutions',
      solutions_count:5, deadline:'2026-12-05',
      impact:'very_high', prize:'₹20 Lakhs',
      tags:['FinTech','Mobile','Microfinance','AI'],
      desc:'Over 190 million Indians remain unbanked. Build a mobile-first financial platform that provides credit scoring, micro-loans, and savings products for those outside the formal banking system.',
      why_matters:'Financial exclusion traps 190 million people in poverty cycles. A 10% increase in financial inclusion can add ₹8,000 to average household income.',
      constraints:'Work on feature phones, support voice in regional languages, comply with RBI regulations.',
      expected_outcome:'Platform serving 1 million underserved users within 12 months with <3% default rate on micro-loans.',
    },
    {
      id:'p009', category:'energy', org_id:'o7',
      title:'Energy Optimization for Industrial Facilities',
      org:'TERI Foundation',
      location:'Gujarat, Maharashtra',
      difficulty:2, status:'pilot', stage:'pilot',
      solutions_count:4, deadline:'2026-09-30',
      impact:'high', prize:'₹16 Lakhs',
      tags:['IoT','Energy','ML','Industry'],
      desc:'Indian SMEs waste 25–35% of energy due to inefficient machinery operation and lack of monitoring. Build an intelligent energy optimization system for small manufacturing units.',
      why_matters:'SMEs account for 45% of India\'s energy consumption. A 20% reduction would save ₹30,000 crore annually in energy costs while reducing carbon emissions by 50 million tonnes.',
      constraints:'Affordable sensor installation cost, minimal disruption to operations, simple dashboard for non-technical staff.',
      expected_outcome:'IoT monitoring system reducing energy waste by 20–30% within 6 months of deployment.',
    },
    {
      id:'p010', category:'cybersecurity', org_id:'o3',
      title:'Cybersecurity for Small Businesses',
      org:'AICTE Innovation Cell',
      location:'Pan India',
      difficulty:2, status:'open', stage:'solutions',
      solutions_count:3, deadline:'2026-12-30',
      impact:'medium', prize:'₹12 Lakhs',
      tags:['Cybersecurity','SaaS','SME','AI'],
      desc:'60% of SMEs suffer a cyber attack within 6 months of setup, and 60% of those shut down within 6 months of the attack. Build affordable cybersecurity tools designed for non-technical SME owners.',
      why_matters:'India has 63 million MSMEs. A single breach costs on average ₹8 lakh. Protecting even 5% can prevent ₹25,000 crore in annual losses.',
      constraints:'Must be plug-and-play, no IT staff required, ₹999/month pricing cap.',
      expected_outcome:'SME security platform blocking 95% of common attack vectors, deployable in under 30 minutes.',
    },
    {
      id:'p011', category:'agriculture', org_id:'o1',
      title:'Smart Irrigation and Soil Monitoring',
      org:'National Agriculture Innovation Lab',
      location:'Rajasthan, Punjab',
      difficulty:2, status:'open', stage:'solutions',
      solutions_count:5, deadline:'2026-11-20',
      impact:'high', prize:'₹18 Lakhs',
      tags:['IoT','Agriculture','Water','Sensors'],
      desc:'Irrigation accounts for 80% of India\'s freshwater use, but 50% is wasted. Build a precision irrigation system using soil sensors and weather data to optimize water usage.',
      why_matters:'Farmers can save 40% water while increasing yields by 15% with precision irrigation. Scaled across Punjab alone, this saves 8 billion litres of water daily.',
      constraints:'Must work with existing pump infrastructure, solar-powered sensors, cost under ₹5,000 per acre.',
      expected_outcome:'IoT-based irrigation system achieving 35% water saving and 15% yield increase in pilot farms.',
    },
    {
      id:'p012', category:'socialimpact', org_id:'o6',
      title:'Assistive Technology for Persons with Disabilities',
      org:'Ministry of Education',
      location:'Pan India',
      difficulty:2, status:'open', stage:'solutions',
      solutions_count:3, deadline:'2026-12-15',
      impact:'high', prize:'₹15 Lakhs',
      tags:['AI','Accessibility','Mobile','NLP'],
      desc:'Over 26 million people with disabilities in India lack access to digital tools designed for their needs. Build affordable, accessible technology that enables independent participation in education and employment.',
      why_matters:'Only 36% of disabled persons in India are employed. Better assistive technology can double employment rates and dramatically improve quality of life.',
      constraints:'Must meet WCAG 2.1 accessibility standards, work offline, support multiple disability types.',
      expected_outcome:'Cross-disability assistive platform used by 500,000 persons within 12 months.',
    },
  ],

  /* ── Solutions per problem ────────────────────────────── */
  solutions: [
    /* ── Problem p001: Crop Disease Detection ── */
    {
      id:'s001', problem_id:'p001', team_id:'t1',
      title:'CropSense AI',
      team:'AgriNova',
      avatar:'🌱', bg:'#F0FDF4',
      tagline:'Instant AI crop disease diagnosis from a smartphone photo.',
      desc:'A mobile-first platform that uses transfer learning on a dataset of 2M crop images to identify 50+ diseases in real-time, even offline. Works with any basic Android camera.',
      approach:'Transfer Learning + Edge Inference',
      tech:['TensorFlow Lite','React Native','Python','Firebase','Node.js'],
      votes:178, status:'shortlisted',
      ai_scores:{ relevance:24, innovation:18, feasibility:19, impact:19, scalability:9, cost:4, total:93 },
      ai_rank:1, shortlisted:true, top_pick:true,
      strengths:['94% disease detection accuracy','Works completely offline','50+ disease types covered'],
      weaknesses:['Limited to visual symptoms only','Requires good camera quality'],
      submitted:'2026-09-02',
      estimated_cost:'₹8,50,000',
      cost_breakdown:{ development:'₹4,00,000', hardware:'₹50,000', deployment:'₹2,50,000', maintenance:'₹1,50,000' },
    },
    {
      id:'s002', problem_id:'p001', team_id:'t2',
      title:'FarmVision',
      team:'FarmVision Labs',
      avatar:'🛰️', bg:'#EFF6FF',
      tagline:'Satellite crop monitoring with per-field disease alerts.',
      desc:'Uses multispectral satellite imagery to detect crop stress signatures across entire fields, identifying disease outbreaks before they are visible to the naked eye. Sends weekly farm health reports.',
      approach:'Satellite Remote Sensing + ML Anomaly Detection',
      tech:['Sentinel-2 API','Python','GeoTIFF','FastAPI','React'],
      votes:142, status:'shortlisted',
      ai_scores:{ relevance:23, innovation:17, feasibility:17, impact:18, scalability:9, cost:3, total:87 },
      ai_rank:2, shortlisted:true, top_pick:false,
      strengths:['Field-level monitoring without ground sensors','Detects stress before visible symptoms'],
      weaknesses:['Requires internet connectivity','Less precise than in-person diagnosis'],
      submitted:'2026-09-04',
      estimated_cost:'₹12,00,000',
      cost_breakdown:{ development:'₹6,00,000', hardware:'₹0', deployment:'₹4,00,000', maintenance:'₹2,00,000' },
    },
    {
      id:'s003', problem_id:'p001', team_id:'t14',
      title:'VoiceAgri',
      team:'VoiceAgri',
      avatar:'🎙️', bg:'#FAF5FF',
      tagline:'Voice-based crop advisory in 12 regional languages.',
      desc:'A voice-first IVR and mobile app system where farmers describe symptoms in their local language and receive AI-generated diagnosis and treatment advice by voice. No smartphone required.',
      approach:'NLP + Voice AI + USSD',
      tech:['Whisper ASR','Local Intelligence Engine','Twilio','Node.js','PostgreSQL'],
      votes:98, status:'shortlisted',
      ai_scores:{ relevance:22, innovation:16, feasibility:18, impact:17, scalability:8, cost:4, total:85 },
      ai_rank:3, shortlisted:true, top_pick:false,
      strengths:['Zero smartphone requirement','12 languages supported','Extremely accessible'],
      weaknesses:['Cannot visually verify symptoms','Lower accuracy than image-based'],
      submitted:'2026-09-05',
      estimated_cost:'₹5,20,000',
      cost_breakdown:{ development:'₹2,50,000', hardware:'₹0', deployment:'₹1,70,000', maintenance:'₹1,00,000' },
    },
    {
      id:'s004', problem_id:'p001', team_id:'t9',
      title:'AgroSense IoT',
      team:'AquaSense Labs',
      avatar:'📡', bg:'#F0FDFA',
      tagline:'Ground sensors for real-time soil and plant health monitoring.',
      desc:'A network of affordable solar-powered IoT sensors placed in the field that continuously monitor soil chemistry, moisture, temperature, and pH — factors correlated with early-stage disease.',
      approach:'IoT Sensor Network + Time-Series ML',
      tech:['ESP32','LoRaWAN','InfluxDB','Python','Flutter'],
      votes:76, status:'under_review',
      ai_scores:{ relevance:20, innovation:15, feasibility:16, impact:16, scalability:7, cost:3, total:77 },
      ai_rank:4, shortlisted:false, top_pick:false,
      strengths:['Continuous monitoring 24/7','Detects pre-symptomatic conditions'],
      weaknesses:['High upfront sensor cost','Requires technical installation'],
      submitted:'2026-09-06',
      estimated_cost:'₹18,00,000',
      cost_breakdown:{ development:'₹4,00,000', hardware:'₹12,00,000', deployment:'₹1,00,000', maintenance:'₹1,00,000' },
    },
    {
      id:'s005', problem_id:'p001', team_id:'t8',
      title:'CropCircle Community',
      team:'GreenLoop',
      avatar:'🌍', bg:'#F0FDF4',
      tagline:'Crowdsourced disease reporting with community early warning.',
      desc:'A peer-to-peer platform where farmers report disease sightings, AI validates reports, and alerts are sent to nearby farmers before the disease spreads. Includes expert consultation.',
      approach:'Crowdsourcing + AI Validation',
      tech:['React Native','Node.js','PostGIS','TensorFlow','AWS'],
      votes:65, status:'under_review',
      ai_scores:{ relevance:19, innovation:14, feasibility:18, impact:16, scalability:8, cost:4, total:79 },
      ai_rank:5, shortlisted:false, top_pick:false,
      strengths:['Network effect grows value','Expert validation layer'],
      weaknesses:['Dependent on farmer adoption','Potential misinformation risk'],
      submitted:'2026-09-07',
      estimated_cost:'₹4,80,000',
      cost_breakdown:{ development:'₹3,00,000', hardware:'₹0', deployment:'₹1,00,000', maintenance:'₹80,000' },
    },

    /* ── Problem p002: Rural Healthcare Diagnostics ── */
    {
      id:'s010', problem_id:'p002', team_id:'t15',
      title:'SepsisSense AI',
      team:'SepsisSense',
      avatar:'🧠', bg:'#EFF6FF',
      tagline:'Edge AI for early sepsis detection on existing ICU hardware.',
      desc:'A lightweight edge-AI model monitoring 12 vitals in real-time from existing ICU sensors, predicting sepsis onset 6–8 hours before clinical manifestation with 94% accuracy. Runs on Raspberry Pi.',
      approach:'Edge ML + IoT Sensor Fusion',
      tech:['TensorFlow Lite','Python','MQTT','Raspberry Pi','React Native'],
      votes:142, status:'shortlisted',
      ai_scores:{ relevance:24, innovation:18, feasibility:18, impact:19, scalability:8, cost:5, total:92 },
      ai_rank:1, shortlisted:true, top_pick:true,
      strengths:['94% detection accuracy','No new hardware required','6–8 hr early warning'],
      weaknesses:['Sepsis-specific, not general diagnostics'],
      submitted:'2026-09-01',
      estimated_cost:'₹6,50,000',
      cost_breakdown:{ development:'₹4,00,000', hardware:'₹1,00,000', deployment:'₹1,00,000', maintenance:'₹50,000' },
    },
    {
      id:'s011', problem_id:'p002', team_id:'t3',
      title:'BioWatch Portable',
      team:'BioWatch',
      avatar:'⌚', bg:'#F0FDFA',
      tagline:'Wearable diagnostic patches for continuous vital monitoring.',
      desc:'Federated wearable mesh of biosensor patches monitoring 8 biomarkers continuously. Uses federated learning to improve accuracy across hospital networks without sharing patient data.',
      approach:'Federated Learning + Wearable Mesh',
      tech:['Federated Learning','Bluetooth 5.0','ARM Cortex','Node.js','InfluxDB'],
      votes:115, status:'shortlisted',
      ai_scores:{ relevance:23, innovation:19, feasibility:16, impact:18, scalability:8, cost:3, total:87 },
      ai_rank:2, shortlisted:true, top_pick:false,
      strengths:['Privacy-preserving federated learning','Continuous monitoring','9 biomarkers tracked'],
      weaknesses:['Higher upfront hardware cost'],
      submitted:'2026-09-03',
      estimated_cost:'₹22,00,000',
      cost_breakdown:{ development:'₹5,00,000', hardware:'₹14,00,000', deployment:'₹2,00,000', maintenance:'₹1,00,000' },
    },
    {
      id:'s012', problem_id:'p002', team_id:'t4',
      title:'RuralDiag Platform',
      team:'RuralHealth Labs',
      avatar:'🏥', bg:'#FFF1F2',
      tagline:'Telemedicine with AI-assisted pre-screening for rural ASHA workers.',
      desc:'A telemedicine platform with AI pre-screening that enables ASHA workers to conduct digital consultations, with AI triage prioritizing cases for remote doctors.',
      approach:'Telemedicine + AI Triage',
      tech:['WebRTC','React','TensorFlow','FastAPI','PostgreSQL'],
      votes:89, status:'under_review',
      ai_scores:{ relevance:22, innovation:14, feasibility:18, impact:17, scalability:8, cost:4, total:83 },
      ai_rank:3, shortlisted:false, top_pick:false,
      strengths:['Leverages existing ASHA network','Low training requirement'],
      weaknesses:['Requires internet connectivity for video'],
      submitted:'2026-09-05',
    },

    /* ── Problem p009: Energy Optimization (in pilot) ── */
    {
      id:'s020', problem_id:'p009', team_id:'t13',
      title:'EcoGrid Smart Energy',
      team:'EcoGrid',
      avatar:'⚡', bg:'#FEFCE8',
      tagline:'AI energy monitoring and optimization for industrial facilities.',
      desc:'IoT sensors + ML analytics platform that monitors real-time energy consumption across machines, predicts peak load, and automatically optimizes usage patterns to reduce waste.',
      approach:'IoT + Reinforcement Learning',
      tech:['ESP32','MQTT','InfluxDB','Python','TensorFlow','Grafana'],
      votes:124, status:'in_pilot',
      ai_scores:{ relevance:24, innovation:16, feasibility:19, impact:18, scalability:8, cost:4, total:89 },
      ai_rank:1, shortlisted:true, top_pick:true,
      strengths:['28% avg energy reduction','ROI in 8 months','Real-time optimization'],
      weaknesses:['Requires sensor installation downtime'],
      submitted:'2026-08-15',
      estimated_cost:'₹9,80,000',
      cost_breakdown:{ development:'₹3,50,000', hardware:'₹4,50,000', deployment:'₹1,00,000', maintenance:'₹80,000' },
    },
  ],

  /* ── Collaborations ───────────────────────────────────── */
  collaborations: [
    {
      id:'col1', problem_id:'p001',
      sol_a:'s001', sol_b:'s002',
      name_a:'CropSense AI', name_b:'FarmVision',
      team_a:'AgriNova', team_b:'FarmVision Labs',
      compat:94, status:'accepted',
      rationale:'CropSense AI provides on-device image diagnosis while FarmVision offers field-wide satellite monitoring. Together they cover both per-plant and per-field scales.',
      evolved_title:'Integrated Rural Crop Intelligence Platform',
      evolved_desc:'A combined platform delivering both in-field smartphone diagnosis and satellite-level field monitoring, giving farmers a complete early warning and advisory system.',
      features_a:['AI image diagnosis','Offline mode','Voice advisory'],
      features_b:['Satellite monitoring','Field health maps','Weekly reports'],
    },
    {
      id:'col2', problem_id:'p001',
      sol_a:'s001', sol_b:'s003',
      name_a:'CropSense AI', name_b:'VoiceAgri',
      team_a:'AgriNova', team_b:'VoiceAgri',
      compat:81, status:'proposed',
      rationale:'CropSense AI\'s visual diagnosis combined with VoiceAgri\'s multilingual voice interface would serve both smartphone and non-smartphone users.',
      evolved_title:'CropSense Voice',
      evolved_desc:'AI crop disease detection accessible via both visual image analysis and voice-based consultation, covering 100% of farmer demographics regardless of device type.',
      features_a:['Image-based diagnosis','50+ diseases'],
      features_b:['12 language voice support','No smartphone needed','USSD access'],
    },
    {
      id:'col3', problem_id:'p002',
      sol_a:'s010', sol_b:'s011',
      name_a:'SepsisSense AI', name_b:'BioWatch Portable',
      team_a:'SepsisSense', team_b:'BioWatch',
      compat:94, status:'active',
      rationale:'SepsisSense provides edge inference and existing hardware integration; BioWatch adds federated privacy and wearable data acquisition.',
      evolved_title:'SepsisMesh Intelligence',
      evolved_desc:'A federated, edge-native sepsis intelligence system with real-time wearable monitoring, privacy-preserving learning, and 7+ hour early warning windows.',
      features_a:['Edge ML inference','ICU hardware integration','Real-time alerts'],
      features_b:['Federated learning','Wearable patches','Privacy preservation'],
    },
  ],

  /* ── Pilots ───────────────────────────────────────────── */
  pilots: [
    {
      id:'pilot1', solution_id:'s020', problem_id:'p009',
      title:'EcoGrid Smart Energy — Industrial Pilot',
      solution:'EcoGrid Smart Energy', team:'EcoGrid',
      org:'TERI Foundation', location:'Surat Industrial Estate',
      start:'2026-07-01', end:'2026-10-31', status:'in_progress',
      progress:65, current_stage:'Phase 2 — Optimization',
      ai_eval_score:89,
      objective:'Validate that real-time IoT monitoring and AI-driven optimization can reduce industrial energy consumption by at least 20% in a live manufacturing environment.',
      scope:'3 factory units · 45 machines · ~200 workers',
      num_users:200, team_size:6,
      success_criteria:['Energy reduction ≥ 20%','System uptime ≥ 99%','ROI payback ≤ 12 months','Operator adoption ≥ 80%'],
      estimated_cost:'₹9,80,000',
      milestones:[
        { id:'m1', title:'Sensor Installation',       date:'2026-07-10', status:'done',   icon:'🔧', desc:'IoT sensors installed across 45 machines in 3 factory units.' },
        { id:'m2', title:'Data Pipeline Validation',  date:'2026-07-25', status:'done',   icon:'📡', desc:'Real-time data flow validated at 500ms polling interval.' },
        { id:'m3', title:'Baseline Measurement',      date:'2026-08-10', status:'done',   icon:'📊', desc:'Pre-optimization energy baseline established across all units.' },
        { id:'m4', title:'AI Model Deployment',       date:'2026-08-25', status:'done',   icon:'🤖', desc:'RL optimization model deployed and running in advisory mode.' },
        { id:'m5', title:'Active Optimization Phase', date:'2026-09-15', status:'active', icon:'⚡', desc:'Automated energy adjustments running. Monitoring for 8 weeks.' },
        { id:'m6', title:'Final Evaluation',          date:'2026-10-20', status:'pending',icon:'✅', desc:'Full KPI review and scale decision by stakeholders.' },
      ],
      kpis:[
        { label:'Energy Reduction',    target:'20%',   actual:'28%',   status:'exceeded', direction:'up',   unit:'%' },
        { label:'Cost Savings/Month',  target:'₹2.4L', actual:'₹3.1L', status:'exceeded', direction:'up',   unit:'' },
        { label:'System Uptime',       target:'99%',   actual:'99.7%', status:'exceeded', direction:'up',   unit:'%' },
        { label:'ROI Payback Period',  target:'12mo',  actual:'8mo',   status:'exceeded', direction:'up',   unit:'' },
        { label:'CO₂ Reduction',       target:'15%',   actual:'22%',   status:'exceeded', direction:'up',   unit:'%' },
        { label:'Operator Adoption',   target:'80%',   actual:'74%',   status:'on_track', direction:'up',   unit:'%' },
      ],
      pilot_score: 88,
      results:{ what_worked:'Real-time monitoring dramatically reduced peak load inefficiencies. Factory managers quickly adopted the dashboard.', what_didnt:'Initial sensor calibration took longer than expected. Voice alerts were less used than anticipated.', recommendation:'Scale to 200 factories across Gujarat. Add predictive maintenance module.' },
      decision: { status:'Approved', verdict:'Scale', date:'Pending Oct 2026', reason:'Pilot demonstrates 28% energy reduction vs 20% target. ROI payback of 8 months vs 12 month target.', reviewer:'TERI Foundation Review Board' },
    },
    {
      id:'pilot2', solution_id:'s010', problem_id:'p002',
      title:'SepsisMesh Intelligence — Hospital Pilot',
      solution:'SepsisMesh Intelligence', team:'SepsisSense + BioWatch (Evolved)',
      org:'Apollo Health Foundation', location:'Rajiv Gandhi District Hospital, Pune',
      start:'2026-08-01', end:'2026-10-31', status:'in_progress',
      progress:55, current_stage:'Phase 1 — Clinical Trial',
      ai_eval_score:92,
      objective:'Clinically validate that federated edge AI can detect sepsis onset ≥4 hours earlier than standard nursing observation, improving patient outcomes in rural district hospitals.',
      scope:'3 ICU wards · 30–100 patients · 12 nursing staff',
      num_users:30, team_size:8,
      success_criteria:['Early detection rate ≥ 85%','False positive rate < 15%','Alert lead time ≥ 4 hours','Nurse adoption ≥ 70%'],
      estimated_cost:'₹28,50,000',
      milestones:[
        { id:'m1', title:'Infrastructure Setup',      date:'2026-08-05', status:'done',   icon:'🔧', desc:'Edge nodes & sensor mesh installed in 3 ICU wards.' },
        { id:'m2', title:'Data Pipeline Testing',     date:'2026-08-20', status:'done',   icon:'📡', desc:'Real-time data ingestion and federated sync validated.' },
        { id:'m3', title:'Model Calibration',         date:'2026-09-01', status:'done',   icon:'🧬', desc:'AI model calibrated to local patient population (91% accuracy).' },
        { id:'m4', title:'Clinical Trial Phase 1',    date:'2026-09-15', status:'active', icon:'🏥', desc:'Live monitoring of 30 ICU patients by nursing staff.' },
        { id:'m5', title:'Clinical Trial Phase 2',    date:'2026-10-01', status:'pending',icon:'📊', desc:'Expand to 100 patients, measure full outcome delta.' },
        { id:'m6', title:'Final Evaluation',          date:'2026-10-25', status:'pending',icon:'✅', desc:'Full KPI review, stakeholder sign-off, scale decision.' },
      ],
      kpis:[
        { label:'Early Sepsis Detection', target:'85%',  actual:'91%',  status:'exceeded', direction:'up',   unit:'%' },
        { label:'False Positive Rate',    target:'<15%', actual:'6%',   status:'exceeded', direction:'up',   unit:'%' },
        { label:'Alert Lead Time',        target:'4hr',  actual:'7.2hr',status:'exceeded', direction:'up',   unit:'' },
        { label:'Nurse Adoption',         target:'70%',  actual:'84%',  status:'exceeded', direction:'up',   unit:'%' },
        { label:'Mortality Reduction',    target:'20%',  actual:'31%',  status:'exceeded', direction:'up',   unit:'%' },
        { label:'Cost per Alert',         target:'₹50',  actual:'₹12',  status:'exceeded', direction:'up',   unit:'' },
      ],
      pilot_score: 91,
      results:{ what_worked:'Edge inference dramatically reduces alert latency. Nurses adopted the system quickly with minimal training.', what_didnt:'Initial wearable patch adhesion issues in high-perspiration patients.', recommendation:'State-wide rollout to 200 rural hospitals. Partner with 3 state governments.' },
      decision: { status:'Recommended', verdict:'Approve for Scale', date:'Pending Oct 2026', reason:'91% detection, 31% mortality reduction, 84% adoption all exceed targets significantly.', reviewer:'Apollo Foundation Review Board' },
    },
  ],

  /* ── Activity Feed ────────────────────────────────────── */
  activities: [
    { id:'a1', type:'solution',     icon:'💡', bg:'#EFF6FF', text:'<strong>CropSense AI</strong> submitted to Early Crop Disease Detection', time:'2 hours ago' },
    { id:'a2', type:'ai',           icon:'🤖', bg:'#F0FDF4', text:'AI analysis completed for <strong>Affordable Rural Healthcare Diagnostics</strong> — 5 solutions scored', time:'4 hours ago' },
    { id:'a3', type:'shortlist',    icon:'🏆', bg:'#FFFBEB', text:'<strong>SepsisSense AI</strong> shortlisted with score 92/100', time:'5 hours ago' },
    { id:'a4', type:'collab',       icon:'🤝', bg:'#FAF5FF', text:'Collaboration request sent to <strong>FarmVision Labs</strong> (94% match)', time:'8 hours ago' },
    { id:'a5', type:'pilot',        icon:'🚀', bg:'#F0FDFA', text:'<strong>EcoGrid Smart Energy</strong> pilot milestone completed — Active Optimization Phase', time:'1 day ago' },
    { id:'a6', type:'submission',   icon:'📝', bg:'#F0FDF4', text:'<strong>BioWatch Portable</strong> submitted to Rural Healthcare Diagnostics', time:'1 day ago' },
    { id:'a7', type:'collab',       icon:'🤝', bg:'#FAF5FF', text:'Collaboration between <strong>SepsisSense + BioWatch</strong> accepted — Workspace open', time:'2 days ago' },
    { id:'a8', type:'decision',     icon:'✅', bg:'#F0FDF4', text:'<strong>EcoGrid pilot</strong> on track — 28% energy reduction exceeded 20% target', time:'3 days ago' },
  ],

  /* ── Attention items ──────────────────────────────────── */
  attention: [
    { id:'at1', type:'action', icon:'🤖', text:'Review AI analysis results for "Early Crop Disease Detection" — 3 solutions shortlisted', href:'ai-analysis.html' },
    { id:'at2', type:'warn',   icon:'🤝', text:'Collaboration request from BioWatch awaiting your response (expires in 2 days)', href:'collaborate.html' },
    { id:'at3', type:'action', icon:'🚀', text:'Pilot milestone due: EcoGrid "Final Evaluation" on Oct 20, 2026', href:'pilot.html' },
    { id:'at4', type:'success',icon:'✅', text:'SepsisMesh pilot results available — review before Oct 25 decision date', href:'pilot.html' },
  ],

  /* ── Helpers ──────────────────────────────────────────── */
  getCat(id)        { return this.categories.find(c => c.id === id); },
  getProblem(id)    { return this.problems.find(p => p.id === id); },
  getSolutions(pid) { return this.solutions.filter(s => s.problem_id === pid); },
  getSolution(id)   { return this.solutions.find(s => s.id === id); },
  getTeam(id)       { return this.teams.find(t => t.id === id); },
  getPilot(id)      { return this.pilots.find(p => p.id === id); },
  getCollabs(pid)   { return this.collaborations.filter(c => c.problem_id === pid); },

  scoreClass(s) {
    if (s >= 88) return 'high';
    if (s >= 75) return 'medium';
    return 'low';
  },
  formatDate(d) {
    return new Date(d).toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'});
  },
  daysLeft(d) {
    const diff = new Date(d) - new Date();
    return Math.max(0, Math.ceil(diff / 86400000));
  },
  impactColor(i) {
    if (i === 'very_high') return 'badge-rose';
    if (i === 'high') return 'badge-amber';
    return 'badge-blue';
  },
  stageBadge(s) {
    const map = {
      solutions:'badge-blue', ai_analysis:'badge-purple', shortlisting:'badge-amber',
      collaboration:'badge-teal', pilot:'badge-green',
    };
    return map[s] || 'badge-gray';
  },
  stageLabel(s) {
    const map = {
      solutions:'Collecting Solutions', ai_analysis:'Solution Analysis',
      shortlisting:'Shortlisting', collaboration:'Collaboration', pilot:'In Pilot',
    };
    return map[s] || s;
  },
};
